"""update speed to string

Revision ID: 09925b3e00d7
Revises: f23cf8ef059a
Create Date: 2023-09-01 08:57:58.233529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09925b3e00d7'
down_revision = 'f23cf8ef059a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
