"""add price with server_default for book column

Revision ID: 17e49759b9ac
Revises: a84fc9d43d00
Create Date: 2023-08-04 15:49:32.264713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e49759b9ac'
down_revision = 'a84fc9d43d00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('price', sa.Float(), server_default=sa.text('1'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'price')
    # ### end Alembic commands ###
