"""create new model

Revision ID: 2709ce05fbec
Revises: ee69ce151391
Create Date: 2023-08-09 21:53:43.734199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2709ce05fbec'
down_revision = 'ee69ce151391'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_auto_rescue',
    sa.Column('auto_rescue_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('auto_rescue_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('auto_rescue_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户id'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('auto_rescue_id'),
    comment='ARED 自动救援操作装置'
    )
    op.create_index(op.f('ix_supplier_auto_rescue_auto_rescue_id'), 'supplier_auto_rescue', ['auto_rescue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_auto_rescue_auto_rescue_id'), table_name='supplier_auto_rescue')
    op.drop_table('supplier_auto_rescue')
    # ### end Alembic commands ###
