"""update smb model

Revision ID: 3205d5538e35
Revises: a9d1c6cc1dc3
Create Date: 2023-08-07 18:51:12.898707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3205d5538e35'
down_revision = 'a9d1c6cc1dc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_smart_board', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_smart_board', sa.Column('test', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
