"""update smartb table

Revision ID: 3fa7ad51ca56
Revises: ea6846a5d959
Create Date: 2023-08-06 15:21:52.154192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa7ad51ca56'
down_revision = 'ea6846a5d959'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
