"""add wire rope model

Revision ID: 40763ee87845
Revises: 1758cacb9330
Create Date: 2023-08-14 15:19:17.203158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40763ee87845'
down_revision = '1758cacb9330'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_wire_rope',
    sa.Column('wire_rope_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('wr_contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('wr_product_name', sa.String(length=50), nullable=True, comment='产品名称'),
    sa.Column('wr_dept_name', sa.String(length=50), nullable=True, comment='制造单位'),
    sa.Column('wr_product_testing_cert', sa.String(length=50), nullable=True, comment='检测报告'),
    sa.Column('wr_product_model', sa.String(length=50), nullable=True, comment='规格'),
    sa.Column('wr_product_matric', sa.String(length=10), nullable=True, comment='度量'),
    sa.Column('wr_product_value', sa.Float(), nullable=True, comment='数值'),
    sa.Column('wr_product_num', sa.Integer(), nullable=True, comment='根数'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('wire_rope_id'),
    comment='钢丝绳'
    )
    op.create_index(op.f('ix_supplier_wire_rope_wire_rope_id'), 'supplier_wire_rope', ['wire_rope_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_wire_rope_wire_rope_id'), table_name='supplier_wire_rope')
    op.drop_table('supplier_wire_rope')
    # ### end Alembic commands ###
