"""create db

Revision ID: 5fc61efbfdd1
Revises: e64915a830f4
Create Date: 2023-08-06 12:20:50.279466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc61efbfdd1'
down_revision = 'e64915a830f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
