"""update smartb_id

Revision ID: 60f780fb8a55
Revises: fd2a79557c69
Create Date: 2023-08-06 12:36:38.351951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f780fb8a55'
down_revision = 'fd2a79557c69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_supplier_smart_board_smartb_id'), 'supplier_smart_board', ['smartb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_smart_board_smartb_id'), table_name='supplier_smart_board')
    # ### end Alembic commands ###
