"""update smb model

Revision ID: 643ee5c184b2
Revises: 951f6719e7bc
Create Date: 2023-08-07 10:58:25.200158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643ee5c184b2'
down_revision = '951f6719e7bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_lvct_board',
    sa.Column('lvctb_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位名称'),
    sa.Column('lvct_model', sa.String(length=100), nullable=True, comment='产品型号'),
    sa.Column('lvct_manufacture_batch_no', sa.String(length=100), nullable=True, comment='制造批次号'),
    sa.Column('lvct_type_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('lvct_manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户id'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('lvctb_id'),
    comment='(含有电子元件的安全电路)LVCT1板'
    )
    op.create_index(op.f('ix_supplier_lvct_board_lvctb_id'), 'supplier_lvct_board', ['lvctb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_lvct_board_lvctb_id'), table_name='supplier_lvct_board')
    op.drop_table('supplier_lvct_board')
    # ### end Alembic commands ###
