"""create new model

Revision ID: 6668b992a49c
Revises: 987517d678f2
Create Date: 2023-08-11 14:58:38.789578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6668b992a49c'
down_revision = '987517d678f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
