"""create new model

Revision ID: 772e0a911135
Revises: 6668b992a49c
Create Date: 2023-08-12 12:40:31.430164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772e0a911135'
down_revision = '6668b992a49c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
