"""create new model

Revision ID: 7b3008052098
Revises: 388a422a7fd3
Create Date: 2023-08-13 08:38:09.536255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3008052098'
down_revision = '388a422a7fd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_buffer',
    sa.Column('buffer_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('project_name', sa.String(length=100), nullable=True, comment='项目名称'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_speed', sa.Float(), nullable=True, comment='速度m/s'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_batch_no', sa.String(length=100), nullable=True, comment='产品批次号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('buffer_id'),
    comment='缓冲器'
    )
    op.create_index(op.f('ix_supplier_buffer_buffer_id'), 'supplier_buffer', ['buffer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_buffer_buffer_id'), table_name='supplier_buffer')
    op.drop_table('supplier_buffer')
    # ### end Alembic commands ###
