"""create new model

Revision ID: 8711d0abcc68
Revises: 2709ce05fbec
Create Date: 2023-08-10 06:39:47.890164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8711d0abcc68'
down_revision = '2709ce05fbec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_ic_card',
    sa.Column('icard_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('icard_model', sa.String(length=100), nullable=True, comment='IC卡型号'),
    sa.Column('icard_no', sa.String(length=100), nullable=True, comment='IC卡编号'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('icard_id'),
    comment='IC卡'
    )
    op.create_index(op.f('ix_supplier_ic_card_icard_id'), 'supplier_ic_card', ['icard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_ic_card_icard_id'), table_name='supplier_ic_card')
    op.drop_table('supplier_ic_card')
    # ### end Alembic commands ###
