"""update dept_id to dept_name

Revision ID: 951f6719e7bc
Revises: 200e74e8ed59
Create Date: 2023-08-07 08:21:04.601421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951f6719e7bc'
down_revision = '200e74e8ed59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_smart_board', sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位名称'))
    op.drop_column('supplier_smart_board', 'dept_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_smart_board', sa.Column('dept_id', sa.BIGINT(), nullable=True))
    op.drop_column('supplier_smart_board', 'dept_name')
    # ### end Alembic commands ###
