"""create new model

Revision ID: 987517d678f2
Revises: f16aae0ca1c8
Create Date: 2023-08-11 14:56:34.797759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987517d678f2'
down_revision = 'f16aae0ca1c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_speed_limiter',
    sa.Column('safe_brake_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('project_name', sa.String(length=100), nullable=True, comment='项目名称'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_speed', sa.Float(), nullable=True, comment='速度m/s'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('safe_brake_id'),
    comment='限速器'
    )
    op.create_index(op.f('ix_supplier_speed_limiter_safe_brake_id'), 'supplier_speed_limiter', ['safe_brake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_speed_limiter_safe_brake_id'), table_name='supplier_speed_limiter')
    op.drop_table('supplier_speed_limiter')
    # ### end Alembic commands ###
