"""create new model

Revision ID: 9979853d2e45
Revises: 8711d0abcc68
Create Date: 2023-08-10 10:42:09.201142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9979853d2e45'
down_revision = '8711d0abcc68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_safe_brake',
    sa.Column('safe_brake_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='用户名称'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_speed', sa.Float(), nullable=True, comment='速度m/s'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('safe_brake_id'),
    comment='安全钳'
    )
    op.create_index(op.f('ix_supplier_safe_brake_safe_brake_id'), 'supplier_safe_brake', ['safe_brake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_safe_brake_safe_brake_id'), table_name='supplier_safe_brake')
    op.drop_table('supplier_safe_brake')
    # ### end Alembic commands ###
