"""update smb model

Revision ID: a9d1c6cc1dc3
Revises: 643ee5c184b2
Create Date: 2023-08-07 15:30:31.669360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d1c6cc1dc3'
down_revision = '643ee5c184b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_smart_board', sa.Column('test', sa.String(length=100), nullable=True, comment='备注'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_smart_board', 'test')
    # ### end Alembic commands ###
