"""new SupplierRopeHead table

Revision ID: b84e702ba82e
Revises: 7722a1530d10
Create Date: 2023-08-09 08:48:21.101595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84e702ba82e'
down_revision = '7722a1530d10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_RopeHead',
    sa.Column('ropehc_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('ropehc_model', sa.String(length=100), nullable=True, comment='产品型号'),
    sa.Column('ropehc_manufacture_batch_no', sa.String(length=100), nullable=True, comment='制造批次号'),
    sa.Column('ropehc_type_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('ropehc_manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户id'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('ropehc_id'),
    comment='绳头组合'
    )
    op.create_index(op.f('ix_supplier_RopeHead_ropehc_id'), 'supplier_RopeHead', ['ropehc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_RopeHead_ropehc_id'), table_name='supplier_RopeHead')
    op.drop_table('supplier_RopeHead')
    # ### end Alembic commands ###
