"""create new model

Revision ID: b86346127f99
Revises: 7b3008052098
Create Date: 2023-08-13 14:09:23.279162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86346127f99'
down_revision = '7b3008052098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_brake',
    sa.Column('brake_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('brake_id'),
    comment='制动器'
    )
    op.create_index(op.f('ix_supplier_brake_brake_id'), 'supplier_brake', ['brake_id'], unique=False)
    op.create_table('supplier_safety_device',
    sa.Column('safety_device_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('safety_device_id'),
    comment='轿厢保护装置'
    )
    op.create_index(op.f('ix_supplier_safety_device_safety_device_id'), 'supplier_safety_device', ['safety_device_id'], unique=False)
    op.create_table('supplier_traction_machine',
    sa.Column('traction_machine_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('traction_machine_id'),
    comment='驱动主机'
    )
    op.create_index(op.f('ix_supplier_traction_machine_traction_machine_id'), 'supplier_traction_machine', ['traction_machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_traction_machine_traction_machine_id'), table_name='supplier_traction_machine')
    op.drop_table('supplier_traction_machine')
    op.drop_index(op.f('ix_supplier_safety_device_safety_device_id'), table_name='supplier_safety_device')
    op.drop_table('supplier_safety_device')
    op.drop_index(op.f('ix_supplier_brake_brake_id'), table_name='supplier_brake')
    op.drop_table('supplier_brake')
    # ### end Alembic commands ###
