"""update price value for book column

Revision ID: bf14f7aae2ee
Revises: 7618d6f7c1e4
Create Date: 2023-08-04 15:45:25.154316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf14f7aae2ee'
down_revision = '7618d6f7c1e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
