"""create db

Revision ID: e64915a830f4
Revises: 
Create Date: 2023-08-06 12:16:23.519820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64915a830f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_smart_board',
    sa.Column('smartb_id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='制造单位ID'),
    sa.Column('smartb_model', sa.String(length=100), nullable=True, comment='产品型号'),
    sa.Column('smartb_manufacture_batch_no', sa.String(length=100), nullable=True, comment='制造批次号'),
    sa.Column('smartb_type_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('smartb_manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.PrimaryKeyConstraint('smartb_id'),
    comment='（含有电子元件的安全电路）SMART主板'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_smart_board')
    # ### end Alembic commands ###
