"""update smartb table

Revision ID: ea6846a5d959
Revises: 60f780fb8a55
Create Date: 2023-08-06 12:46:13.641160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6846a5d959'
down_revision = '60f780fb8a55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_smart_board', sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'))
    op.add_column('supplier_smart_board', sa.Column('update_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'))
    op.add_column('supplier_smart_board', sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_smart_board', 'remark')
    op.drop_column('supplier_smart_board', 'update_time')
    op.drop_column('supplier_smart_board', 'create_time')
    # ### end Alembic commands ###
