"""create new model

Revision ID: ee69ce151391
Revises: f46365e8adeb
Create Date: 2023-08-09 20:27:18.678243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee69ce151391'
down_revision = 'f46365e8adeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_rope_head', sa.Column('ropehc_name', sa.String(length=100), nullable=True, comment='设备品种'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_rope_head', 'ropehc_name')
    # ### end Alembic commands ###
