"""create new model

Revision ID: f23cf8ef059a
Revises: 
Create Date: 2023-08-25 16:03:59.319787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23cf8ef059a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_auto_rescue',
    sa.Column('auto_rescue_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('auto_rescue_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('auto_rescue_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户id'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('auto_rescue_id'),
    comment='ARED 自动救援操作装置'
    )
    op.create_index(op.f('ix_supplier_auto_rescue_auto_rescue_id'), 'supplier_auto_rescue', ['auto_rescue_id'], unique=False)
    op.create_table('supplier_brake_machine',
    sa.Column('brake_machine_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('brake_machine_id'),
    comment='制动器'
    )
    op.create_index(op.f('ix_supplier_brake_machine_brake_machine_id'), 'supplier_brake_machine', ['brake_machine_id'], unique=False)
    op.create_table('supplier_buffer',
    sa.Column('buffer_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('project_name', sa.String(length=100), nullable=True, comment='项目名称'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_speed', sa.Float(), nullable=True, comment='速度m/s'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_batch_no', sa.String(length=100), nullable=True, comment='产品批次号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('buffer_id'),
    comment='缓冲器'
    )
    op.create_index(op.f('ix_supplier_buffer_buffer_id'), 'supplier_buffer', ['buffer_id'], unique=False)
    op.create_table('supplier_ic_card',
    sa.Column('icard_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('icard_model', sa.String(length=100), nullable=True, comment='IC卡型号'),
    sa.Column('icard_no', sa.String(length=100), nullable=True, comment='IC卡编号'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('icard_id'),
    comment='IC卡'
    )
    op.create_index(op.f('ix_supplier_ic_card_icard_id'), 'supplier_ic_card', ['icard_id'], unique=False)
    op.create_table('supplier_lvct_board',
    sa.Column('lvctb_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位名称'),
    sa.Column('lvct_model', sa.String(length=100), nullable=True, comment='产品型号'),
    sa.Column('lvct_manufacture_batch_no', sa.String(length=100), nullable=True, comment='制造批次号'),
    sa.Column('lvct_type_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('lvct_manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户id'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('lvctb_id'),
    comment='(含有电子元件的安全电路)LVCT1板'
    )
    op.create_index(op.f('ix_supplier_lvct_board_lvctb_id'), 'supplier_lvct_board', ['lvctb_id'], unique=False)
    op.create_table('supplier_rope_head',
    sa.Column('rope_head_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('ropehc_name', sa.String(length=100), nullable=True, comment='设备品种'),
    sa.Column('ropehc_model', sa.String(length=100), nullable=True, comment='产品型号'),
    sa.Column('ropehc_manufacture_batch_no', sa.String(length=100), nullable=True, comment='制造批次号'),
    sa.Column('ropehc_type_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('ropehc_manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户id'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('rope_head_id'),
    comment='绳头组合'
    )
    op.create_index(op.f('ix_supplier_rope_head_rope_head_id'), 'supplier_rope_head', ['rope_head_id'], unique=False)
    op.create_table('supplier_safe_brake',
    sa.Column('safe_brake_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='用户名称'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_speed', sa.Float(), nullable=True, comment='速度m/s'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('safe_brake_id'),
    comment='安全钳'
    )
    op.create_index(op.f('ix_supplier_safe_brake_safe_brake_id'), 'supplier_safe_brake', ['safe_brake_id'], unique=False)
    op.create_table('supplier_safety_machine',
    sa.Column('safety_machine_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('safety_machine_id'),
    comment='轿厢保护装置'
    )
    op.create_index(op.f('ix_supplier_safety_machine_safety_machine_id'), 'supplier_safety_machine', ['safety_machine_id'], unique=False)
    op.create_table('supplier_smart_board',
    sa.Column('smartb_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位名称'),
    sa.Column('smartb_model', sa.String(length=100), nullable=True, comment='产品型号'),
    sa.Column('smartb_manufacture_batch_no', sa.String(length=100), nullable=True, comment='制造批次号'),
    sa.Column('smartb_type_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('smartb_manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户id'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('smartb_id'),
    comment='（含有电子元件的安全电路）SMART主板'
    )
    op.create_index(op.f('ix_supplier_smart_board_smartb_id'), 'supplier_smart_board', ['smartb_id'], unique=False)
    op.create_table('supplier_speed_limiter',
    sa.Column('speed_limiter_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('project_name', sa.String(length=100), nullable=True, comment='项目名称'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_speed', sa.Float(), nullable=True, comment='速度m/s'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('speed_limiter_id'),
    comment='限速器'
    )
    op.create_index(op.f('ix_supplier_speed_limiter_speed_limiter_id'), 'supplier_speed_limiter', ['speed_limiter_id'], unique=False)
    op.create_table('supplier_traction_machine',
    sa.Column('traction_machine_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('product_type_name', sa.String(length=100), nullable=True, comment='设备品种名称'),
    sa.Column('product_model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('product_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('product_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('traction_machine_id'),
    comment='驱动主机'
    )
    op.create_index(op.f('ix_supplier_traction_machine_traction_machine_id'), 'supplier_traction_machine', ['traction_machine_id'], unique=False)
    op.create_table('supplier_wire_rope',
    sa.Column('wire_rope_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('wr_contract_no', sa.String(), nullable=True, comment='合同号'),
    sa.Column('wr_product_name', sa.String(length=50), nullable=True, comment='产品名称'),
    sa.Column('wr_dept_name', sa.String(length=50), nullable=True, comment='制造单位'),
    sa.Column('wr_product_testing_cert', sa.String(length=50), nullable=True, comment='检测报告'),
    sa.Column('wr_product_model', sa.String(length=50), nullable=True, comment='规格'),
    sa.Column('wr_product_matric', sa.String(length=10), nullable=True, comment='度量'),
    sa.Column('wr_product_value', sa.Float(), nullable=True, comment='数值'),
    sa.Column('wr_product_num', sa.Integer(), nullable=True, comment='根数'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('wire_rope_id'),
    comment='钢丝绳'
    )
    op.create_index(op.f('ix_supplier_wire_rope_wire_rope_id'), 'supplier_wire_rope', ['wire_rope_id'], unique=False)
    op.create_table('supplier_控制柜',
    sa.Column('control_cabinet_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(length=100), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('batch_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('type_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('user_id', sa.String(length=64), nullable=True, comment='操作用户id'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('type_name', sa.String(length=255), nullable=True, comment='设备品种'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.PrimaryKeyConstraint('control_cabinet_id'),
    comment='控制柜'
    )
    op.create_index(op.f('ix_supplier_控制柜_control_cabinet_id'), 'supplier_控制柜', ['control_cabinet_id'], unique=False)
    op.create_table('supplier_门系统',
    sa.Column('door_system_id', sa.String(), nullable=False, comment='ID号'),
    sa.Column('contract_no', sa.String(length=100), nullable=True, comment='合同号'),
    sa.Column('dept_name', sa.String(length=100), nullable=True, comment='制造单位'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='型号'),
    sa.Column('batch_no', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('type_testing_cert_no', sa.String(length=100), nullable=True, comment='型式试验证书编号'),
    sa.Column('manufacture_date', sa.Date(), nullable=True, comment='制造日期'),
    sa.Column('user_id', sa.String(length=64), nullable=True, comment='操作用户id'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='层门,防火门,玻璃轿门,玻璃轿壁，厅门锁，轿门锁'),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('type_name', sa.String(length=255), nullable=True, comment='设备品种'),
    sa.Column('data_state', sa.String(length=10), nullable=True, comment='数据的状态'),
    sa.PrimaryKeyConstraint('door_system_id'),
    comment='门系统'
    )
    op.create_index(op.f('ix_supplier_门系统_door_system_id'), 'supplier_门系统', ['door_system_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_门系统_door_system_id'), table_name='supplier_门系统')
    op.drop_table('supplier_门系统')
    op.drop_index(op.f('ix_supplier_控制柜_control_cabinet_id'), table_name='supplier_控制柜')
    op.drop_table('supplier_控制柜')
    op.drop_index(op.f('ix_supplier_wire_rope_wire_rope_id'), table_name='supplier_wire_rope')
    op.drop_table('supplier_wire_rope')
    op.drop_index(op.f('ix_supplier_traction_machine_traction_machine_id'), table_name='supplier_traction_machine')
    op.drop_table('supplier_traction_machine')
    op.drop_index(op.f('ix_supplier_speed_limiter_speed_limiter_id'), table_name='supplier_speed_limiter')
    op.drop_table('supplier_speed_limiter')
    op.drop_index(op.f('ix_supplier_smart_board_smartb_id'), table_name='supplier_smart_board')
    op.drop_table('supplier_smart_board')
    op.drop_index(op.f('ix_supplier_safety_machine_safety_machine_id'), table_name='supplier_safety_machine')
    op.drop_table('supplier_safety_machine')
    op.drop_index(op.f('ix_supplier_safe_brake_safe_brake_id'), table_name='supplier_safe_brake')
    op.drop_table('supplier_safe_brake')
    op.drop_index(op.f('ix_supplier_rope_head_rope_head_id'), table_name='supplier_rope_head')
    op.drop_table('supplier_rope_head')
    op.drop_index(op.f('ix_supplier_lvct_board_lvctb_id'), table_name='supplier_lvct_board')
    op.drop_table('supplier_lvct_board')
    op.drop_index(op.f('ix_supplier_ic_card_icard_id'), table_name='supplier_ic_card')
    op.drop_table('supplier_ic_card')
    op.drop_index(op.f('ix_supplier_buffer_buffer_id'), table_name='supplier_buffer')
    op.drop_table('supplier_buffer')
    op.drop_index(op.f('ix_supplier_brake_machine_brake_machine_id'), table_name='supplier_brake_machine')
    op.drop_table('supplier_brake_machine')
    op.drop_index(op.f('ix_supplier_auto_rescue_auto_rescue_id'), table_name='supplier_auto_rescue')
    op.drop_table('supplier_auto_rescue')
    # ### end Alembic commands ###
