"""update smart board table

Revision ID: fd2a79557c69
Revises: 5fc61efbfdd1
Create Date: 2023-08-06 12:23:28.515980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2a79557c69'
down_revision = '5fc61efbfdd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
